# Generated by Django 6.0.1 on 2026-05-29 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=255)),
                ('risk_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('source_url', models.CharField(max_length=255)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.tracker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
